version: '3.2'
 
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: hibernate_orm
      MYSQL_DATABASE: hibernate_orm
      MYSQL_USER: hibernate_orm
      MYSQL_PASSWORD: hibernate_orm
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: